# Generated by Django 4.0.5 on 2022-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bier_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bier',
            name='image',
            field=models.ImageField(upload_to='bier'),
        ),
        migrations.AlterField(
            model_name='biercompany',
            name='logo',
            field=models.ImageField(upload_to='bier_company'),
        ),
    ]
