# Generated by Django 4.0.5 on 2022-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bier_shop', '0002_alter_bier_image_alter_biercompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biercompany',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
